version: '3'
services:
  hugo:
    image: hugo
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    volumes:
      - ./site/:/src/
    ports:
      - "1313:1313"
    command: "hugo server --bind=0.0.0.0 --port=1313"